import { createTypes } from 'reduxsauce';

export default createTypes(`
  CHECKLISTS_FETCH
  CHECKLISTS_FETCH_SUCCESS
  CHECKLISTS_FETCH_FAILURE

  CHECKLIST_UPDATE

  ACTIVE_CHECKLISTS_FETCH
  ACTIVE_CHECKLISTS_FETCH_SUCCESS
  ACTIVE_CHECKLISTS_FETCH_FAILURE
`);