import { createTypes } from 'reduxsauce';

export default createTypes(`
  RESET_DIFFERENCES

  ROOM_CLEAN_DIFFERENCE
  ROOM_CLEAN_DIFFERENCE_READ
  ROOM_CLEAN_DIFFERENCE_IGNORE

  ROOM_MESSAGE_DIFFERENCE
  ROOM_MESSAGE_DIFFERENCE_READ
  ROOM_MESSAGE_DIFFERENCE_IGNORE

  ROOM_UNBLOCK_DIFFERENCE
  ROOM_UNBLOCK_DIFFERENCE_READ
  ROOM_UNBLOCK_DIFFERENCE_IGNORE

  ROOM_RESTOCK_DIFFERENCE
  ROOM_RESTOCK_DIFFERENCE_READ
  ROOM_MESSAGE_DIFFERENCE_IGNORE

  PLANNING_PRIORITY_DIFFERENCE
  PLANNING_PRIORITY_DIFFERENCE_READ
  PLANNING_PRIORITY_DIFFERENCE_IGNORE

  CALENDAR_CHECKIN_DIFFERENCE
  CALENDAR_CHECKIN_DIFFERENCE_READ
  CALENDAR_CHECKIN_DIFFERENCE_IGNORE

  CALENDAR_CHECKOUT_DIFFERENCE
  CALENDAR_CHECKOUT_DIFFERENCE_READ
  CALENDAR_CHECKOUT_DIFFERENCE_IGNORE
`);
