import { createTypes } from 'reduxsauce';

export default createTypes(`
  LOST_FOUND_RESET
  LOST_FOUND_SET_PHOTO
  LOST_FOUND_CLEAR_PHOTO
  LOST_FOUND_SET_DESCRIPTION
  LOST_FOUND_SHOW_NOTIFICATION_WITH_TIMEOUT
`);
