import { createTypes } from 'reduxsauce';

export default createTypes(`
  OUTBOUND_RESET

  OUTBOUND_ROOM_CLEAN_START
  OUTBOUND_ROOM_CLEAN_RESTART
  OUTBOUND_ROOM_CLEAN_PAUSE
  OUTBOUND_ROOM_CLEAN_UNPAUSE
  OUTBOUND_ROOM_CLEAN_FINISH

  OUTBOUND_ROOM_DELAY
  OUTBOUND_ROOM_DND
  OUTBOUND_ROOM_REFUSE
  OUTBOUND_ROOM_VOUCHER
  OUTBOUND_ROOM_INSPECT
  OUTBOUND_ROOM_NO_CHECK
  OUTBOUND_ROOM_CONFIRM_DND
  OUTBOUND_ROOM_CANCEL
  OUTBOUND_ROOM_RESET
  OUTBOUND_ROOM_RESET_FAILURE

  OUTBOUND_ROOM_MODEL_UPDATE
  OUTBOUND_ROOM_ATTENDANT_INSPECT

  OUTBOUND_ROOM_UPDATE_SUCCESS
  OUTBOUND_ROOM_CLEAN_FAILURE
  OUTBOUND_ROOM_UPDATE_FAILURE
  
  OUTBOUND_LOG_OTHER
  OUTBOUND_LOG_CLEAN
  OUTBOUND_LOG_COMPLETED
  OUTBOUND_LOG_FAILURE

  OUTBOUND_SUBMIT_FOUND_ITEM
  OUTBOUND_SUBMIT_FOUND_ITEM_SUCCESS
  OUTBOUND_SUBMIT_FOUND_ITEM_FAILURE

  OUTBOUND_TASK_CREATE
  OUTBOUND_TASK_CREATE_SUCCESS
  OUTBOUND_TASK_CREATE_FAILURE
  OUTBOUND_TASK_PHOTO_SUCCESS
  OUTBOUND_TASK_PHOTO_FAILURE

  OUTBOUND_TASKS_CREATE
  OUTBOUND_TASKS_CREATE_SUCCESS
  OUTBOUND_TASKS_CREATE_FAILURE

  OUTBOUND_TASK_UPDATE
  OUTBOUND_TASK_UPDATE_SUCCESS
  OUTBOUND_TASK_UPDATE_FAILURE

  OUTBOUND_TASK_UPDATE_BATCH
  OUTBOUND_TASK_UPDATE_BATCH_SUCCESS
  OUTBOUND_TASK_UPDATE_BATCH_FAILURE

  OUTBOUND_TASK_REASSIGN
  OUTBOUND_TASK_REASSIGN_SUCCESS
  OUTBOUND_TASK_REASSIGN_FAILURE

  OUTBOUND_TASK_EDIT
  OUTBOUND_TASK_EDIT_SUCCESS
  OUTBOUND_TASK_EDIT_FAILURE

  OUTBOUND_TASK_CONVERT
  OUTBOUND_TASK_CONVERT_SUCCESS
  OUTBOUND_TASK_CONVERT_FAILURE

  OUTBOUND_GLITCH_UPDATE
  OUTBOUND_GLITCH_UPDATE_SUCCESS
  OUTBOUND_GLITCH_UPDATE_FAILURE

  OUTBOUND_NOTIFICATION_CREATE
  OUTBOUND_NOTIFICATION_CREATE_SUCCESS
  OUTBOUND_NOTIFICATION_CREATE_FAILURE
  OUTBOUND_NOTIFICATION_PHOTO_SUCCESS
  OUTBOUND_NOTIFICATION_PHOTO_FAILURE

  OUTBOUND_LF_CREATE_UPLOADING_PHOTO
  OUTBOUND_LF_CREATE_APPLY_PHOTO
  OUTBOUND_LF_PHOTO_FAILURE

  OUTBOUND_LF_SUBMIT
  OUTBOUND_LF_SUBMIT_SUCCESS
  OUTBOUND_LF_SUBMIT_FAILURE

  OUTBOUND_ROOM_MESSAGE_ADD
  OUTBOUND_ROOM_MESSAGE_ADD_FAILURE

  OUTBOUND_ROOM_MESSAGE_REMOVE
  OUTBOUND_ROOM_MESSAGE_REMOVE_FAILURE

  OUTBOUND_ROOM_MESSAGE_UPDATE
  OUTBOUND_ROOM_MESSAGE_UPDATE_FAILURE

  OUTBOUND_INVENTORY_WITHDRAWAL
  OUTBOUND_INVENTORY_WITHDRAWAL_SUCCESS
  OUTBOUND_INVENTORY_WITHDRAWAL_FAILURE
  OUTBOUND_INVENTORY_REJECT
  OUTBOUND_INVENTORY_REJECT_SUCCESS
  OUTBOUND_INVENTORY_REJECT_FAILURE

  OUTBOUND_UPDATE_FOUND_ITEM
  OUTBOUND_UPDATE_FOUND_ITEM_SUCCESS
  OUTBOUND_UPDATE_FOUND_ITEM_FAILURE

  OUTBOUND_FOUND_PHOTO_EXTRA_ITEM
  OUTBOUND_FOUND_PHOTO_EXTRA_ITEM_SUCCESS
  OUTBOUND_FOUND_PHOTO_EXTRA_ITEM_FAILURE

  OUTBOUND_FOUND_UPDATE_PHOTO
  OUTBOUND_FOUND_UPDATE_PHOTO_SUCCESS
  OUTBOUND_FOUND_UPDATE_PHOTO_FAILURE

  OUTBOUND_UPDATE_EXTRA_OPTION
  OUTBOUND_UPDATE_EXTRA_OPTION_SUCCESS
  OUTBOUND_UPDATE_EXTRA_OPTION_FAILURE

  OUTBOUND_NIGHT_PLANNING_BULK
  OUTBOUND_NIGHT_PLANNING_BULK_SUCCESS
  OUTBOUND_NIGHT_PLANNING_BULK_FAILURE

  OUTBOUND_NIGHT_PLANNING_UPDATE
  OUTBOUND_NIGHT_PLANNING_UPDATE_SUCCESS
  OUTBOUND_NIGHT_PLANNING_UPDATE_FAILURE

  OUTBOUND_TASK_UPLOAD_ADD_PHOTO
  OUTBOUND_TASK_SUBMIT_ADD_PHOTO
  OUTBOUND_TASK_SUBMIT_ADD_PHOTO_SUCCESS
  OUTBOUND_TASK_SUBMIT_ADD_PHOTO_FAILURE

  OUTBOUND_TASKS_TO_SOMEDAY
  OUTBOUND_TASKS_TO_SOMEDAY_SUCCESS
  OUTBOUND_TASKS_TO_SOMEDAY_FAILURE

  OUTBOUND_TASKS_FROM_SOMEDAY
  OUTBOUND_TASKS_FROM_SOMEDAY_SUCCESS
  OUTBOUND_TASKS_FROM_SOMEDAY_FAILURE

  OUTBOUND_RETRY_FAILED
  OUTBOUND_REMOVE_FAILED
`);
