import { createTypes } from 'reduxsauce';

export default createTypes(`
  RESET_ROOMS

  ROOM_ACTIVATE
  ROOM_DEACTIVATE

  ROOMS_FETCH
  ROOMS_SUCCESS
  ROOMS_FAILURE
  ROOMS_UPDATES
  ROOMS_UPDATE_READ
  ROOMS_UNBLOCKS
  ROOMS_UNBLOCKS_READ

  ROOM_UPDATE_OPTIMISTIC
  ROOM_UPDATE_SUCCESS

  FLOORS_FETCH
  FLOORS_SUCCESS
  FLOORS_FAILURE

  ROOM_STATUSES_FETCH
  ROOM_STATUSES_SUCCESS
  ROOM_STATUSES_FAILURE

  ROOM_HOUSEKEEPINGS_FETCH
  ROOM_HOUSEKEEPINGS_SUCCESS
  ROOM_HOUSEKEEPINGS_FAILURE

  ROOM_CATEGORY_FETCH
  ROOM_CATEGORY_SUCCESS
  ROOM_CATEGORY_FAILURE

  PLANNINGS_FETCH
  PLANNINGS_SUCCESS
  PLANNINGS_FAILURE

  PLANNINGS_UPDATES
  PLANNINGS_UPDATE_READ

  PLANNING_UPDATE_OPTIMISTIC

  PLANNINGS_NIGHT_FETCH
  PLANNINGS_NIGHT_SUCCESS
  PLANNINGS_NIGHT_FAILURE

  PLANNINGS_RUNNER_FETCH
  PLANNINGS_RUNNER_SUCCESS
  PLANNINGS_RUNNER_FAILURE

  CALENDAR_FETCH
  CALENDAR_SUCCESS
  CALENDAR_FAILURE

  ROOM_NOTES_FETCH
  ROOM_NOTES_SUCCESS
  ROOM_NOTES_FAILURE

  CATALOGS_FETCH
  CATALOGS_SUCCESS
  CATALOGS_FAILURE

  LOST_FETCH
  LOST_FETCH_SUCCESS
  LOST_FETCH_FAILURE

  FOUND_FETCH
  FOUND_FETCH_SUCCESS
  FOUND_FETCH_FAILURE

  TASKS_FETCH
  TASKS_SUCCESS
  TASKS_FAILURE

  TASK_UPDATE_OPTIMISTIC
  TASK_UPDATE_SUCCESS

  HISTORY_FETCH
  HISTORY_SUCCESS
  HISTORY_FAILURE

  BOOKMARK_ADD
  BOOKMARK_REMOVE
  BOOKMARKS_CLEAR

  GUEST_BOOK_FETCH
  GUEST_BOOK_FETCH_SUCCESS
  GUEST_BOOK_FETCH_FAILURE

  PLANNINGS_HOSTS_IN_FETCH
  PLANNINGS_HOSTS_IN_FETCH_SUCCESS
  PLANNINGS_HOSTS_IN_FETCH_FAILURE
  PLANNINGS_HOSTS_OUT_FETCH
  PLANNINGS_HOSTS_OUT_FETCH_SUCCESS
  PLANNINGS_HOSTS_OUT_FETCH_FAILURE

  EXTRA_OPTION_UPDATE_OPTIMISTIC

  UPDATE_ROOMS_INCREMENT
`);
