import { createTypes } from 'reduxsauce';

export default createTypes(`
  UPDATES_RESET

  INVENTORY_ADJUST
  INVENTORY_REJECT
  INVENTORY_RESET
  INVENTORY_FLUSH
  INVENTORY_RESTOCK

  ROOM_CLEAN_START
  ROOM_CLEAN_RESTART
  ROOM_CLEAN_PAUSE
  ROOM_CLEAN_UNPAUSE
  ROOM_CLEAN_FINISH
  ROOM_CLEAN_FLUSH

  ROOM_DELAY
  ROOM_DND
  ROOM_REFUSE
  ROOM_VOUCHER
  ROOM_INSPECT
  ROOM_NO_CHECK
  ROOM_CONFIRM_DND
  ROOM_CANCEL
  ROOM_RESET

  ROOM_HOUSEKEEPING
  ROOM_MOBILE_INSPECT
  ROOM_COMMENT
  ROOM_GUEST_LOCATOR
  ROOM_UNBLOCK
  ROOM_ADD_CHANGE_SHEETS

  ROOM_MESSAGE_ADD
  ROOM_MESSAGE_ADD_SUCCESS

  ROOM_MESSAGE_REMOVE
  ROOM_MESSAGE_REMOVE_SUCCESS

  ROOM_MESSAGE_UPDATE
  ROOM_MESSAGE_UPDATE_SUCCESS

  ROOM_RESTOCK
  ROOM_TURNDOWN

  PLANNING_USER
  PLANNING_NIGHT_USER
  PlANNING_NIGHT_UPDATE

  ROOM_NOTE_ADD
  ROOM_NOTE_REMOVE

  PHOTO_UPLOAD
  PHOTO_UPLOAD_SUCCESS
  PHOTO_UPLOAD_FAILURE

  PHOTO_STORE
  PHOTO_REMOVE

  LOST_ITEM_ADD
  LOST_ITEM_ADD_SUCCESS
  LOST_ITEM_ADD_FAILURE

  LOST_ITEM_SUBMIT
  LOST_ITEM_SUBMIT_SUCCESS
  LOST_ITEM_UPLOADING_PHOTO
  LOST_ITEM_APPLY_PHOTO

  TASK_CREATE
  TASK_UPDATE
  TASK_CONVERT
  TASK_CREATE_BATCH
  TASK_UPDATE_BATCH
  TASK_REASSIGN
  TASK_EDIT
  
  TASK_ADD_PHOTO
  TASK_SUBMIT_PHOTO

  TASK_CREATE_SUBMIT
  TASK_CREATE_UPLOADING_PHOTO
  TASK_CREATE_APPLY_PHOTO
  TASK_CREATE_SUCCESS
  TASK_CREATE_FAILURE

  TASK_SENDING
  TASK_SENDING_SUCCESS
  TASK_SENDING_FAILURE
  TASK_SENDING_RESET

  NOTIFICATION_CREATE  
  NOTIFICATION_CREATE_SUBMIT
  NOTIFICATION_CREATE_UPLOADING_PHOTO
  NOTIFICATION_CREATE_APPLY_PHOTO
  NOTIFICATION_CREATE_SUCCESS
  NOTIFICATION_CREATE_FAILURE

  LOST_FOUND_UPDATE_FOUND_STATUS
  LOST_FOUND_UPDATE_FOUND_STATUS_SUCCESS
  LOST_FOUND_UPDATE_FOUND_STATUS_FAILURE
  
  LOST_FOUND_UPDATE_FOUND_PHOTO
  LOST_FOUND_UPDATE_FOUND_PHOTO_SUCCESS
  LOST_FOUND_UPDATE_FOUND_PHOTO_FAILURE
  LOST_FOUND_EXTRA_APPLY_PHOTO

  EXTRA_OPTION_UPDATE
  EXTRA_OPTION_UPDATE_SUCCESS
  EXTRA_OPTION_UPDATE_FAILURE

  TASKS_TO_SOMEDAY
  TASKS_FROM_SOMEDAY

  SAVE_OUTGOING_HASH
`);
